### PR TITLE
Update deps

### LINKED ISSUE #370: Update deps
With the most recent ClimaAtmos release, v0.15.5, we want to update the Coupler again

### PR DESCRIPTION
**Pull request by valeriabarra**
## Purpose 
Closes #370 

Updates dependencies. In particualar:

```
↑ ClimaAtmos v0.15.4 ⇒ v0.15.5
```

## Content
- Solution implemented:
    - [x] Updated Manifest files
    - [x] Updated ClimaAtmos CLI options    

Review checklist

I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.

In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, and modules, and included relevant documentation.

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by valeriabarra** [comment]
CI passes. Ready for review. Thanks

**Review by juliasloan25 — APPROVED** [review]
Looks good!

**Comment by valeriabarra** [comment]
Thanks. I reviewed the artifacts produced and are identical to `main`. I'm going to merge this.

**Pull request merged**
