### PR TITLE
remove deprecated function calls

### LINKED ISSUE #611: remove deprecated function calls
We have some deprecated function calls in our code. ClimaCore is planning a release today (2/9/24) or next week that will remove support for these, so we need to fix them. We might as well fix deprecated functions from other packages we're using as well. This will clean up many warnings in our tests :)

### PR DESCRIPTION
**Pull request by juliasloan25**
## Purpose 
closes #611

- [x] no behavioral changes

## To-do
- [x] update deprecated ClimaCore functions
- [x] update deprecated ClimaAtmos function

### CODE REVIEW

**Comment by Sbozzolo** [comment]
> note: still seeing Warning: @add_arg_table is deprecated, use @add_arg_table! instead after changes, not sure why

Because of Atmos

**Review by Sbozzolo — APPROVED** [review]
There's a `space.vertical_topology` in `Regridder.jl`.

I wouldn't be surprised if other things were missed: it's hard to find them all. I guess those will surface at some point.

**Comment by juliasloan25** [comment]
> There's a space.vertical_topology in Regridder.jl.

I only find the one that's fixed in this PR

**Comment by Sbozzolo** [comment]
> > There's a space.vertical_topology in Regridder.jl.
> 
> I only find the one that's fixed in this PR

Yes, I missed it!

**Pull request merged**
