### PR TITLE
Update deps and CLI options

### LINKED ISSUE #365: Update dependencies again
Now that ClimaCore v0.10.46 and ClimaAtmos v0.15.4 were released, we want to update the Coupler to use these latest releases.

### PR DESCRIPTION
**Pull request by valeriabarra**
## Purpose 
This PR update dependencies again. 

Closes #365 

## Content
- Solution implemented: Updated all checked-in Manifest files to use latest dependencies. In particular: 

```
↑ ClimaAtmos v0.15.3 ⇒ v0.15.4
↑ ClimaCore v0.10.44 ⇒ v0.10.46
```

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by valeriabarra** [comment]
CI passes and this PR is ready for review. Thanks!

**Comment by valeriabarra** [comment]
@LenkaNovak there seems to be tiny numerical differences in `u` and `precipitation` in the AMIP paper_plots, but qualitatively, the plots haven't changed much. Let me know what you think!

**Review by LenkaNovak — APPROVED** [review]
LGTM, thanks, Valeria! Actually the AMIP run is 20% faster, so something good happened upstream! ;-)

**Comment by valeriabarra** [comment]
> LGTM, thanks, Valeria! Actually the AMIP run is 20% faster, so something good happened upstream! ;-)

Great! It was probably due to ClimaCore v0.10.46. There were some changes in some of the geometric transformations that led to some performance gains.

**Pull request merged**
