### PR TITLE
Update for compatibility with ClimaAtmos@0.3.0

### LINKED ISSUE #97: Plotting problems after the last ClimaAtmos release
Currently plotting anything based off the horizontal center space from `ClimaAtmos@0.2.0` plots a distorted image, whereas plotting exactly the same field in `ClimaAtmos@0.3.0` produces the expected plot. (even with the same versions of `ClimaCorePlots` and `ClimaCore`)

MWE:
```
# boundary_space = h_space # this line is for ClimaAtmos@0.2.0
# boundary_space = spaces.center_space # this line is for ClimaAtmos@0.3.0

local_geometry = Fields.local_geometry_field(boundary_space)
ϕ = local_geometry.coordinates.lat
ff = ones(boundary_space) .* sin.(ϕ .* FT((π/180)))

plot(ff)
savefig("f.png")
```

We need to update `ClimaAtmos` via a new release, as well as make the regrid_space consistent with the boundary space.
Screen Shot 2022-07-21 at 11 33 18 AM
Screen Shot 2022-07-21 at 11 32 58 AM

### PR DESCRIPTION
**Pull request by LenkaNovak**
# PULL REQUEST

with @kmdeck 

## Purpose and Content
Update for the new ClimaAtmos release. 

## Benefits and Risks
- benefit - up to date with current branch, this will fix a plotting bug (#97 )
- risk - change of dependencies

## Linked Issues
- Closes #97 

## Other comments
- we identified an incompatibility in ClimaAtmos, so we will link to [this fix](https://github.com/CliMA/ClimaAtmos.jl/pull/696) until ClimaAtmos@0.4.0 is released. (tagging @charleskawczynski for visibility)

## PR Checklist
- [x] This PR has a corresponding issue OR is linked to an SDI.
- [x] I have followed CliMA's codebase [contribution](https://clima.github.io/ClimateMachine.jl/latest/Contributing/) and [style](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) guidelines OR N/A.
- [x] I have followed CliMA's [documentation policy](https://github.com/CliMA/policies/wiki/Documentation-Policy).
- [x] I have checked all issues and PRs and I certify that this PR does not duplicate an open PR.
- [x] I linted my code on my local machine prior to submission OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code used in an integration test OR N/A.
- [x] All tests ran successfully on my local machine OR N/A.
- [x] All classes, modules, and function contain docstrings OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by jb-mackay — APPROVED** [review]

**Comment by LenkaNovak** [comment]
@jb-mackay there were clashes with ClimaAtmos and the packages therein, so I had to remove `DocStringExtensions = "0.9"` in Project.toml. Is that ok for the time being?

**Comment by LenkaNovak** [comment]
(resolved on slack)

**Pull request merged**
