### PR TITLE
Update amip_target_topo_diagedmf.yml

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

This yaml file will be for the target simulation we want to show at the VESRI meeting. This PR updates the corresponding atmos yaml file, and removes a few redundant configs. We will add more configs (e.g. aerosols) to this file when they are ready.

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
Do we want to maybe add every single config here? Including the one in default_config. This would isolate the run from possible changes and one has to "opt-in" changing configurations

**Comment by Sbozzolo** [comment]
> Do we want to maybe add every single config here? Including the one in default_config. This would isolate the run from possible changes and one has to "opt-in" changing configurations

Oops, I though this was Atmos. We can do that in atmos (if we want to)

**Review by Sbozzolo — APPROVED** [review]

**Comment by juliasloan25** [comment]
Thanks Zhaoyi! Should we change the runs that are output in the coupler table to use this setup too, since this is our target?

**Comment by szy21** [comment]
> Thanks Zhaoyi! Should we change the runs that are output in the coupler table to use this setup too, since this is our target?

We would probably need to lower the resolution of this run in order to run a multi-year simulation for the VESRI meeting, so I think we can keep the one we have in the coupler table. Which is the config file you are using for the coupler table now?

**Pull request merged**
