### PR TITLE
Improvements to longruns pipeline

### PR DESCRIPTION
**Pull request by Sbozzolo**
This PR:
- Removed the longrun depot. This avoid potential depot corruptions 
- Switches from mpiexec to srun for a more reliable MPI experience.

### CODE REVIEW

**Review by LenkaNovak — APPROVED** [review]
LGTM, just checked this fix here: https://buildkite.com/clima/climacoupler-longruns/builds/448

**Comment by LenkaNovak** [comment]
> LGTM, just checked this fix here: https://buildkite.com/clima/climacoupler-longruns/builds/448

Actually, even though the init is now passing, it looks like we need to constrain the [Plots dependency](https://buildkite.com/clima/climacoupler-longruns/builds/448#018dc7c4-0456-415a-9776-18ee34be6297) again?

**Comment by Sbozzolo** [comment]
I cleaned up a couple of things in the manifest and it looks like it's working:

https://buildkite.com/clima/climacoupler-longruns/builds/449

**Comment by szy21** [comment]
There seem to be some artifact errors: https://buildkite.com/clima/climacoupler-longruns/builds/449#018dc853-7e02-4d95-a6d0-8e9acaeb0b47/219-8134

**Comment by szy21** [comment]
Also all the breaking simulations hang. Maybe we need to add `SLURM_KILL_BAD_EXIT: 1` to the pipeline?

**Comment by Sbozzolo** [comment]
> Also all the breaking simulations hang. Maybe we need to add `SLURM_KILL_BAD_EXIT: 1` to the pipeline?

Added

> There seem to be some artifact errors: https://buildkite.com/clima/climacoupler-longruns/builds/449#018dc853-7e02-4d95-a6d0-8e9acaeb0b47/219-8134

This seems like a random filesystem failure. I am trying again.

**Comment by Sbozzolo** [comment]
`ArgumentError: '/central/scratch/esm/slurm-buildkite/climacoupler-longruns/450/depot/default/artifacts/845995bb777cf5a3920541585d62c087f62e5cb5`

I think this is a race condition on downloading artifacts :(

https://buildkite.com/clima/climacoupler-longruns/builds/450#018dcc4a-c9ef-4d0d-84b0-2c7ec9ccddb5

**Comment by LenkaNovak** [comment]
> `ArgumentError: '/central/scratch/esm/slurm-buildkite/climacoupler-longruns/450/depot/default/artifacts/845995bb777cf5a3920541585d62c087f62e5cb5`
> 
> I think this is a race condition on downloading artifacts :(
> 
> https://buildkite.com/clima/climacoupler-longruns/builds/450#018dcc4a-c9ef-4d0d-84b0-2c7ec9ccddb5

Hmm, I haven't seen this one before. Maybe we should deal with the topo files before running the job like the rest of the artifacts [here](https://github.com/CliMA/ClimaCoupler.jl/blob/gb/longruns/.buildkite/longruns/pipeline.yml#L41), rather than on the fly when initiating atmos?

**Comment by Sbozzolo** [comment]
> > `ArgumentError: '/central/scratch/esm/slurm-buildkite/climacoupler-longruns/450/depot/default/artifacts/845995bb777cf5a3920541585d62c087f62e5cb5`
> > I think this is a race condition on downloading artifacts :(
> > https://buildkite.com/clima/climacoupler-longruns/builds/450#018dcc4a-c9ef-4d0d-84b0-2c7ec9ccddb5
> 
> Hmm, I haven't seen this one before. Maybe we should deal with the topo files before running the job like the rest of the artifacts [here](https://github.com/CliMA/ClimaCoupler.jl/blob/gb/longruns/.buildkite/longruns/pipeline.yml#L41), rather than on the fly when initiating atmos?

Ideally we should fix that (xref: https://github.com/CliMA/ClimaLand.jl/issues/467), but yes, best to ensure that all the artifacts are downloaded before starting the simulations for the time being.

**Comment by Sbozzolo** [comment]
Okay, this time everything is looking good:

https://buildkite.com/clima/climacoupler-longruns/builds/451

**Pull request merged**
