### PR TITLE
Update Manifest files

### LINKED ISSUE #356: Update dependencies
ClimaAtmos v0.15.3 was just released, so we want to update dependencies in the Coupler again to keep it up to date with current releases.

### PR DESCRIPTION
**Pull request by valeriabarra**
## Purpose 
This PR updates to the latest dependencies.

Closes #356 

## Content
- Solution implemented: Updated `Manifest.toml` files using `] up`

Review checklist

I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.

In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, and modules, and included relevant documentation.

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by valeriabarra** [comment]
CI passes and this PR is ready for review. 
Cc: @LenkaNovak

**Review by LenkaNovak — APPROVED** [review]
LGTM! No behavioral changes from the previous merge! 🚀

**Comment by valeriabarra** [comment]
> LGTM! No behavioral changes from the previous merge! rocket

Great! I rebased and will merge

**Pull request merged**
