### PR TITLE
Update climacommon to 2024_04_05

### PR DESCRIPTION
**Pull request by Sbozzolo**
🤖 Beep boop. I am GabrieleBOT. 🤖 Good news! I found a way to reduce unnecessary precompilations! Have you ever noticed that when you move to a GPU node from a CPU one (or viceversa), everything has to be recompiled again? Or sometimes it seems that you are always precompiling... Well, this is partially because the nodes on the Caltech cluster have different architectures, and Julia compiles for the native one, but when you move to a new architecture, the compiled code has to be invalidated and recompiled again. With the latest version of climacommon, I force Julia to always compile for all the possible targets in our cluster. Buildkite pipelines partially do this with the JULIA_TARGET_CPU, but the strings there are incorrect. This PR fixes that too.

### CODE REVIEW

**Comment by juliasloan25** [comment]
@Sbozzolo I just saw this `tmp/` directory error on another branch too ([build](https://buildkite.com/clima/climacoupler-ci/builds/3216#018eb05a-55de-40d8-8cab-baf1fb5fa3f1)). Have you seen it anywhere else?

**Comment by Sbozzolo** [comment]
> @Sbozzolo I just saw this `tmp/` directory error on another branch too ([build](https://buildkite.com/clima/climacoupler-ci/builds/3216#018eb05a-55de-40d8-8cab-baf1fb5fa3f1)). Have you seen it anywhere else?

No, but I think I know what it is

**Review by juliasloan25 — APPROVED** [review]

**Comment by juliasloan25** [comment]
> > @Sbozzolo I just saw this `tmp/` directory error on another branch too ([build](https://buildkite.com/clima/climacoupler-ci/builds/3216#018eb05a-55de-40d8-8cab-baf1fb5fa3f1)). Have you seen it anywhere else?
> 
> No, but I think I know what it is

What is it?

**Comment by Sbozzolo** [comment]
> > > @Sbozzolo I just saw this `tmp/` directory error on another branch too ([build](https://buildkite.com/clima/climacoupler-ci/builds/3216#018eb05a-55de-40d8-8cab-baf1fb5fa3f1)). Have you seen it anywhere else?
> > 
> > 
> > No, but I think I know what it is
> 
> What is it?

It's the recent change I applied to try to fix the slurm timeouts. The alternative itself times out, so the folders don't get created.

**Pull request merged**
