### PR TITLE
rename dt_save_to_disk to dt_save_state_to_disk

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

Following recent changes in ClimaAtmos.

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Review by juliasloan25 — COMMENTED** [review]
I think there are two other files that need to be updated: `config/longrun_configs/amip_target_topo.yml` and `amip_target.yml`

**Comment by szy21** [comment]
> I think there are two other files that need to be updated: `config/longrun_configs/amip_target_topo.yml` and `amip_target.yml`

Thanks! I have fixed them.

**Review by juliasloan25 — APPROVED** [review]

**Review by LenkaNovak — APPROVED** [review]
LGTM. In case you're using it, the parsed args in `local_checks.sh` do not take precedence over the config files, so the arguments here may need to be refactored into the relevant yml config files.

**Comment by szy21** [comment]
> LGTM. In case you're using it, the parsed args in `local_checks.sh` do not take precedence over the config files, so the arguments here may need to be refactored into the relevant yml config files.

Good to know, thanks!

**Pull request merged**
