### PR TITLE
use julia v1.9

### LINKED ISSUE #307: Upgrade to Julia 1.9
Julia v1.9 has been released and we should update our manifests to use this new version.

Addressed by #437

Before updating ourselves, we're waiting for at least ClimaAtmos to update, which is itself waiting for ClimaCore to update.
- https://github.com/CliMA/ClimaAtmos.jl/pull/1659, https://github.com/CliMA/ClimaAtmos.jl/issues/2001, https://github.com/CliMA/ClimaAtmos.jl/issues/2037
- https://github.com/CliMA/ClimaCore.jl/pull/1235, https://github.com/CliMA/ClimaCore.jl/pull/1417, https://github.com/CliMA/ClimaCore.jl/pull/1420

### PR DESCRIPTION
**Pull request by juliasloan25**
## Purpose 
Update from julia v1.8 to 1.9.

Closes #307

Note: [moist_mpi_earth_dynamical_sea_ice](https://github.com/CliMA/ClimaCoupler.jl/blob/main/experiments/AMIP/moist_mpi_earth_dynamical_sea_ice/Manifest.toml#L3) is currently using julia 1.7.5 still (not even 1.8) - are we still maintaining this?

## To-do
- [x] update GHA
- [x] update buildkite pipeline
- [x] update Manifests
- [x] test

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Review by LenkaNovak — APPROVED** [review]
LGTM, thanks @juliasloan25 !

**Comment by juliasloan25** [comment]
bors cancel

**Pull request merged**
