### PR TITLE
Add concurrent group for init

### PR DESCRIPTION
**Pull request by Sbozzolo**
Ensures that only one init job is run at the same time across pipelines.

### CODE REVIEW

**Comment by LenkaNovak** [comment]
Looks good, but how do I know it's working? 🤔

**Comment by Sbozzolo** [comment]
Just start two pipelines at the same time (e.g., from the web interface). You should see that one will be waiting for an agent until the other one has finished (the init step)

**Review by LenkaNovak — APPROVED** [review]
Sounds good, tried and tested. Thank you, @Sbozzolo !

**Comment by Sbozzolo** [comment]
Thanks for testing!

**Pull request merged**
