### PR TITLE
Make `modules` uniform across buildkite pipelines

### PR DESCRIPTION
**Pull request by akshaysridhar**
Update to use `climacommon` (auto latest)
```
	modified:   .buildkite/amip/pipeline.yml
	modified:   .buildkite/benchmarks/pipeline.yml
	modified:   .buildkite/hierarchies/pipeline.yml
	modified:   .buildkite/longruns/pipeline.yml
	modified:   .buildkite/nightly/pipeline.yml
	modified:   .buildkite/pipeline.yml
```

### CODE REVIEW

**Comment by akshaysridhar** [comment]
Is there a reason we currently pin modules in certain pipelines to May 24 versions ?

**Comment by juliasloan25** [comment]
Thanks for doing this! I had included this in the Julia 1.11 update #1026 but we can have it separate too (and I missed our regular CI pipeline)

I think it would be better to specify `climacommon/2024_10_09` rather than just `climacommon`, so that we can control when we update to the latest version. For example, `2024_10_09` was released with Julia 1.11 when ClimaCore wasn't yet compatible with it, leading to some bugs in ClimaCoupler. If we use a specific version, we can make any required changes when we update

**Comment by akshaysridhar** [comment]
Great, thank you @juliasloan25! I had started this to PR as a solution to some nightly pipeline instantiation issues I was seeing - I agree that being more specific with the version gives us more control ; (I'm happy to close this and fold it into the #1026 PR)

**Comment by akshaysridhar** [comment]
Closing as this is addressed in #1026 with @juliasloan25 fixing the regular CI pipeline as well.

**Pull request closed without merging**
