### PR TITLE
change target atmos config filename

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

Modifies the longrun config as the atmos longrun config file has been renamed.

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Review by LenkaNovak — APPROVED** [review]
LGTM, thank you!

**Comment by LenkaNovak** [comment]
FYI @juliasloan25 is currenly merging https://github.com/CliMA/ClimaCoupler.jl/pull/561, in case this matters for the new auto-merge.

**Comment by juliasloan25** [comment]
> FYI @juliasloan25 is currenly merging #561, in case this matters for the new auto-merge.

Since the two PRs don't have any conflicts, I think there shouldn't be any problem merging (or auto-merging) both :)

**Comment by LenkaNovak** [comment]
Great, thanks for checking, @juliasloan25 !

**Comment by szy21** [comment]
Thanks for checking!

**Pull request merged**
