### PR TITLE
Update .gitignore w/ vscode artifacts

### PR DESCRIPTION
**Pull request by valeriabarra**
## Purpose 
Updates `.gitignore` to add the artifacts generated by the VScode editor (which most of us use)

## Content
- Updated `.gitignore`

Review checklist

- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by valeriabarra** [comment]
bors try

**Review by juliasloan25 — APPROVED** [review]
Looks good. We should also open an issue describing that NCDatasets v0.12.17 has breaking changes and we need to update for them and revert this compat accordingly.

**Comment by valeriabarra** [comment]
> Looks good. We should also open an issue describing that NCDatasets v0.12.17 has breaking changes and we need to update for them and revert this compat accordingly.

Sounds good. Do you mind doing that? If not, just let me know and I'll do it

**Comment by valeriabarra** [comment]
> NCDatasets v0.12.17 has breaking changes

okay, done.
https://github.com/CliMA/ClimaCoupler.jl/issues/325

**Pull request merged**
